## Used Car Price Prediction

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("cardekho_imputated.csv",index_col=[0])
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

### 1.Data Cleaning

In [3]:
## check null values
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [4]:
df.drop(['car_name','brand'],axis=1)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...
19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [5]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [6]:
# Getting All Different Types Of Features

num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))

cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features :', len(cat_features))

discrete_features = [feature for feature in num_features if len(df[feature].unique()) < 25]
print("Num of Discrete Features :", len(discrete_features))

continuous_features = [feature for feature in num_features if feature not in discrete_features]
print("Num of Continuous Features :", len(continuous_features))

Num of Numerical Features : 7
Num of Categorical Features : 6
Num of Discrete Features : 2
Num of Continuous Features : 5

In [7]:
print("Numerical Features:")
print(num_features)

print("\nCategorical Features:")
print(cat_features)

print("\nDiscrete Features:")
print(discrete_features)

print("\nContinuous Features:")
print(continuous_features)

Numerical Features:
['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']

Categorical Features:
['car_name', 'brand', 'model', 'seller_type', 'fuel_type', 'transmission_type']

Discrete Features:
['vehicle_age', 'seats']

Continuous Features:
['km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [8]:
## Independent and dependent features
from sklearn.model_selection import train_test_split
X=df.drop(['selling_price','car_name','brand'],axis=1)
y=df['selling_price']

In [9]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [10]:
df['seller_type'].value_counts()

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [11]:
df['fuel_type'].value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [12]:
df['transmission_type'].value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [13]:
df['seats'].value_counts()

seats
5    12910
7     1922
8      311
6      127
4       77
9       55
2        7
0        2
Name: count, dtype: int64

### 2.Feature Engeenering

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [15]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [16]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

# Numerical Features
num_features = X.select_dtypes(exclude='object').columns

# Categorical Features
onehot_columns = ['seller_type', 'fuel_type', 'transmission_type']

# Transformers
numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

# Preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('OneHotEncoder', oh_transformer, onehot_columns),
        ('StandardScaler', numeric_transformer, num_features)
    ],remainder='passthrough'
)

# Transform data
X = preprocessor.fit_transform(X)

In [17]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [18]:
## seprate dataset into train and test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=42)
X_train.shape,X_test.shape

((10017, 14), (5394, 14))

### 4.Model training and selection

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [24]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)

    return mae, rmse, r2_square

In [25]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(random_state=42),
    "AdaBoost Regressor": AdaBoostRegressor(random_state=42),
    "Gradient Boosting Regressor": GradientBoostingRegressor(random_state=42)
}

results = []

for model_name, model in models.items():
    try:
        model.fit(X_train, y_train)

        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)

        train_mae, train_rmse, train_r2 = evaluate_model(y_train, y_train_pred)
        test_mae, test_rmse, test_r2 = evaluate_model(y_test, y_test_pred)

        results.append({
            "model": model_name,
            "train_mae": train_mae,
            "train_rmse": train_rmse,
            "train_r2": train_r2,
            "test_mae": test_mae,
            "test_rmse": test_rmse,
            "test_r2": test_r2
        })

        print(f"\n{model_name}")
        print(f"Training  -> RMSE: {train_rmse:.4f}, MAE: {train_mae:.4f}, R2: {train_r2:.4f}")
        print(f"Testing   -> RMSE: {test_rmse:.4f}, MAE: {test_mae:.4f}, R2: {test_r2:.4f}")
        print("=" * 60)

    except Exception as e:
        print(f"{model_name} failed with error: {e}")
        print("=" * 60)

pd.DataFrame(results)

Linear Regression
Training  -> RMSE: 566886.4692, MAE: 269119.6052, R2: 0.6145
Testing   -> RMSE: 500063.7987, MAE: 281496.7609, R2: 0.6600
============================================================

Lasso
Training  -> RMSE: 566886.4788, MAE: 269118.6487, R2: 0.6145
Testing   -> RMSE: 500062.9273, MAE: 281495.7621, R2: 0.6601
============================================================

Ridge
Training  -> RMSE: 566887.4187, MAE: 269071.5770, R2: 0.6145
Testing   -> RMSE: 500044.7874, MAE: 281438.8493, R2: 0.6601
============================================================

K-Neighbors Regressor
Training  -> RMSE: 349556.7355, MAE: 93001.9367, R2: 0.8534
Testing   -> RMSE: 276013.7826, MAE: 115617.5612, R2: 0.8964
============================================================

Decision Tree
Training  -> RMSE: 19952.2590, MAE: 4507.4906, R2: 0.9995
Testing   -> RMSE: 367268.7625, MAE: 135592.0452, R2: 0.8166
============================================================

Random Forest Regressor
Training  -> RMSE: 147054.6910, MAE: 39807.4663, R2: 0.9741
Testing   -> RMSE: 243612.9129, MAE: 105715.4324, R2: 0.9193
============================================================

AdaBoost Regressor
Training  -> RMSE: 419537.5304, MAE: 314886.0162, R2: 0.7889
Testing   -> RMSE: 459302.6049, MAE: 333640.9353, R2: 0.7132
============================================================

Gradient Boosting Regressor
Training  -> RMSE: 196118.2970, MAE: 109714.6074, R2: 0.9539
Testing   -> RMSE: 273226.1410, MAE: 127186.7778, R2: 0.8985
============================================================

,model,train_mae,train_rmse,train_r2,test_mae,test_rmse,test_r2
0,Linear Regression,269119.605215,566886.469236,0.614521,281496.760917,500063.798707,0.660049
1,Lasso,269118.648737,566886.478764,0.614521,281495.762069,500062.927287,0.660051
2,Ridge,269071.577021,566887.418670,0.614520,281438.849297,500044.787404,0.660075
3,K-Neighbors Regressor,93001.936708,349556.735468,0.853431,115617.561179,276013.782581,0.896432
4,Decision Tree,4507.490599,19952.259041,0.999522,135592.045174,367268.762482,0.816628
5,Random Forest Regressor,39807.466320,147054.691038,0.974060,105715.432409,243612.912854,0.919320
6,AdaBoost Regressor,314886.016219,419537.530355,0.788870,333640.935348,459302.604918,0.713211
7,Gradient Boosting Regressor,109714.607393,196118.296993,0.953864,127186.777790,273226.140971,0.898513

In [26]:
print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("Type:", type(X_train))

X_train shape: (10017, 14)
X_test shape : (5394, 14)
Type: <class 'numpy.ndarray'>